### ISSUE TITLE
npm run build and npm run test do not work

### ISSUE THREAD

**Issue by themoonrat** [pixijs/pixi-ui#34]
Fresh checkout, on Windows 10, NodeJS 10.16.0, and after an npm i

dave.moore@LAP00281 C:\projects\webgl\3rdparty-external\pixi-ui
$ npm run build

> puxi.js-monorepo@1.0.0 build C:\projects\webgl\3rdparty-external\pixi-ui
> rollup -c && lerna run extract-api --no-bail

packages\tween\src\index.ts → packages\tween\lib\puxi-tween.cjs, packages\tween\lib\puxi-tween.mjs...
created packages\tween\lib\puxi-tween.cjs, packages\tween\lib\puxi-tween.mjs in 228ms

packages\tween\src\index.ts → packages\tween\dist\puxi-tween.js...
created packages\tween\dist\puxi-tween.js in 127ms

packages\core\src\index.ts → packages\core\lib\puxi-core.cjs, packages\core\lib\puxi-core.mjs...
created packages\core\lib\puxi-core.cjs, packages\core\lib\puxi-core.mjs in 1.3s

packages\core\src\index.ts → packages\core\dist\puxi-core.js...
created packages\core\dist\puxi-core.js in 897ms

bundles\puxi.js\src\index.ts → bundles\puxi.js\lib\puxi.cjs, bundles\puxi.js\lib\puxi.mjs...(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@puxi/core (imported by bundles\puxi.js\src\index.ts)
@puxi/tween (imported by bundles\puxi.js\src\index.ts)
created bundles\puxi.js\lib\puxi.cjs, bundles\puxi.js\lib\puxi.mjs in 26ms

bundles\puxi.js\src\index.ts → bundles\puxi.js\dist\puxi.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@puxi/core (imported by bundles\puxi.js\src\index.ts)
@puxi/tween (imported by bundles\puxi.js\src\index.ts)
(!) Missing global variable names
Use output.globals to specify browser global variable names corresponding to external modules
@puxi/core (guessing 'core')
@puxi/tween (guessing 'tween')
created bundles\puxi.js\dist\puxi.js in 23ms
lerna notice cli v3.20.2
lerna info Executing command in 3 packages: "npm run extract-api"
lerna info run Ran npm script 'extract-api' in '@puxi/tween' in 3.0s:

> @puxi/tween@1.0.0 extract-api C:\projects\webgl\3rdparty-external\pixi-ui\packages\tween
> tsc; api-extractor run

error TS6053: File ';.ts' not found.
error TS6053: File 'api-extractor.ts' not found.
error TS6053: File 'run.ts' not found.

lerna info run Ran npm script 'extract-api' in '@puxi/core' in 2.9s:

> @puxi/core@1.0.0 extract-api C:\projects\webgl\3rdparty-external\pixi-ui\packages\core
> tsc; api-extractor run

error TS6053: File ';.ts' not found.
error TS6053: File 'api-extractor.ts' not found.
error TS6053: File 'run.ts' not found.

lerna info run Ran npm script 'extract-api' in 'puxi.js' in 0.9s:

> puxi.js@0.0.0 extract-api C:\projects\webgl\3rdparty-external\pixi-ui\bundles\puxi.js
> api-extractor run

lerna ERR! Received non-zero exit code 2 during execution
lerna success run Ran npm script 'extract-api' in 3 packages in 6.8s:
lerna success - puxi.js
lerna success - @puxi/core
lerna success - @puxi/tween
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! puxi.js-monorepo@1.0.0 build: `rollup -c && lerna run extract-api --no-bail`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the puxi.js-monorepo@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

$ npm run test

> puxi.js-monorepo@1.0.0 test C:\projects\webgl\3rdparty-external\pixi-ui
> mocha -r jsdom-global/register --exit

(node:7832) ExperimentalWarning: The fs.promises API is experimental

Error: Cannot find module '@pixi/filter-drop-shadow'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\projects\webgl\3rdparty-external\pixi-ui\packages\core\lib\puxi-core.cjs:14:24)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\projects\webgl\3rdparty-external\pixi-ui\packages\core\test\layout-manager\AnchorLayout.test.js:7:6)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at C:\projects\webgl\3rdparty-external\pixi-ui\node_modules\mocha\lib\mocha.js:314:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\projects\webgl\3rdparty-external\pixi-ui\node_modules\mocha\lib\mocha.js:311:14)
    at C:\projects\webgl\3rdparty-external\pixi-ui\node_modules\mocha\lib\mocha.js:347:12
    at new Promise (<anonymous>)
    at Mocha.loadFilesAsync (C:\projects\webgl\3rdparty-external\pixi-ui\node_modules\mocha\lib\mocha.js:346:12)
    at singleRun (C:\projects\webgl\3rdparty-external\pixi-ui\node_modules\mocha\lib\cli\run-helpers.js:107:15)
    at exports.runMocha (C:\projects\webgl\3rdparty-external\pixi-ui\node_modules\mocha\lib\cli\run-helpers.js:144:11)
    at Object.exports.handler (C:\projects\webgl\3rdparty-external\pixi-ui\node_modules\mocha\lib\cli\run.js:306:11)
    at Object.runCommand (C:\projects\webgl\3rdparty-external\pixi-ui\node_modules\mocha\node_modules\yargs\lib\command.js:242:26)
    at Object.parseArgs [as _parseArgs] (C:\projects\webgl\3rdparty-external\pixi-ui\node_modules\mocha\node_modules\yargs\yargs.js:1096:28)
    at Object.parse (C:\projects\webgl\3rdparty-external\pixi-ui\node_modules\mocha\node_modules\yargs\yargs.js:575:25)
    at Object.exports.main (C:\projects\webgl\3rdparty-external\pixi-ui\node_modules\mocha\lib\cli\cli.js:68:6)
    at Object.<anonymous> (C:\projects\webgl\3rdparty-external\pixi-ui\node_modules\mocha\bin\mocha:133:29)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puxi.js-monorepo@1.0.0 test: `mocha -r jsdom-global/register --exit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puxi.js-monorepo@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by SukantPal** [comment]
Looks like `@pixi/filter-drop-shadow` isn't in the dependencies. Try installing `@pixi/filter-drop-shadow`.

The extract-api is broken right now because of something in the legacy tweeting and ease system. I am going to replace them with `@puxi/tween` wherever they are used.

**Comment by themoonrat** [comment]
Installing @pixi/filter-drop-shadow as a dev dependency got passed that bit of the install, cheers.

npm run test now fails on

$ npm run test

> puxi.js-monorepo@1.0.0 test C:\projects\webgl\3rdparty-external\pixi-ui
> mocha -r jsdom-global/register --exit

(node:17468) ExperimentalWarning: The fs.promises API is experimental

ReferenceError: performance is not defined
    at new Ticker (C:\projects\webgl\3rdparty-external\pixi-ui\packages\core\lib\puxi-core.cjs:5718:21)
    at Object.<anonymous> (C:\projects\webgl\3rdparty-external\pixi-ui\packages\core\lib\puxi-core.cjs:5764:17)


and npm run docs fails on
dave.moore@LAP00281 C:\projects\webgl\3rdparty-external\pixi-ui
$ npm run docs

> puxi.js-monorepo@1.0.0 docs C:\projects\webgl\3rdparty-external\pixi-ui
> rm -rf ./dist/docs/* && jsdoc -c jsdoc.conf.json -R README.md;

'rm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puxi.js-monorepo@1.0.0 docs: `rm -rf ./dist/docs/* && jsdoc -c jsdoc.conf.json -R README.md;`
